[book]
authors = ["smallyunet"]
language = "zh"
multilingual = false
src = "."
title = "Ground-Up Blockchain"

[build]
build-dir = "docs"
create-missing = false

[output.html]
cname = "gub.smallyu.net"
additional-css = ["./style.css"]
google-analytics = "G-TV14T76LST"
